Repository thurbridi/py-rudolph, pull requests merged in 2019-05, with the labels that each got.

#48 Cleaning
  .gitignore
  data/empty_scene.obj
  data/rotation_scene.obj
  mypy.ini
  src/cgcodecs.py
  src/clipping.py
  src/graphics.py
  src/linalg.py
  src/scene.py
  src/transformations.py
  src/windows.py
Labels: bug, enhancement

#49 Bezier
  src/clipping.py
  src/graphics.py
  src/windows.py
  ui/newobjectdialog.ui
Labels: feature

#50 Entregável 1.5
  .gitignore
  data/empty_scene.obj
  data/rotation_scene.obj
  mypy.ini
  src/cgcodecs.py
  src/clipping.py
  src/graphics.py
  src/linalg.py
  src/scene.py
  src/transformations.py
  src/windows.py
  ui/newobjectdialog.ui
Labels: enhancement, feature

#53 Clipping fix
  src/clipping.py
  src/windows.py
Labels: bug

#55 Clipping fix
  src/clipping.py
Labels: bug

#52 Curvas B-Spline.
  data/all_obj.obj
  data/b-spline.obj
  src/cgcodecs.py
  src/clipping.py
  src/graphics.py
  src/transformations.py
  src/windows.py
Labels: bug, feature
