Repository thurbridi/py-rudolph, pull requests merged in 2019-04, with the labels that each got.

#4 Added window navigation and zoom using mouse inputs
  src/graphics.py
  src/windows.py
  ui/mainwindow.ui
Labels: feature

#10 Added pipenv support and setup/run script
  Pipfile
  Pipfile.lock
  README.md
  setup.sh
Labels: feature

#11 Hcoordinates
  src/graphics.py
  src/windows.py
Labels: enhancement, feature

#18 Output text
  src/windows.py
  ui/mainwindow.ui
Labels: feature

#23 Conserta bugs relacionados às transformações e proporção da window
  src/graphics.py
  src/transformations.py
  src/windows.py
  ui/mainwindow.ui
Labels: bug

#25 Resolve #16 #17: leitura e escrita de arquivos .obj
  data/empty_scene.obj
  data/test_scene.obj
  src/cgcodecs.py
  src/graphics.py
  src/viewport.py
  src/windows.py
  ui/mainwindow.ui
Labels: feature

#24 Resolve #15: Rotação da Window
  data/test_scene2.obj
  src/graphics.py
  src/windows.py
  ui/mainwindow.ui
Labels: feature

#35 Resolve #30: Clipping de pontos, retas e polígonos não-preenchidos.
  src/clipping.py
  src/graphics.py
  src/linalg.py
  src/windows.py
  ui/mainwindow.ui
Labels: feature

#40 Resolve #38: Área de clipping rotacionando junto com a window
  src/clipping.py
  src/graphics.py
  src/windows.py
Labels: bug

#37 Resolve #33: Polígonos preenchidos
  data/test_scene3.obj
  data/test_scene4.obj
  src/cgcodecs.py
  src/clipping.py
  src/graphics.py
  src/windows.py
  ui/newobjectdialog.ui
Labels: feature

#36 Resolve #36 #26: Modificação da viewport e remoção de objetos
  src/windows.py
  ui/mainwindow.ui
  ui/newobjectdialog.ui
Labels: enhancement, feature
